// examples/qwik/src/server.tsx
/// <reference types="vite/client" />
import { render, jsx } from "@qwik.dev/core";
import root from "./root";

export default {
  async fetch(req: Request): Promise<Response> {
    return new Response(indexHTML(), {
      headers: {
        "Content-Type": "text/html",
      },
    });
  },
};

function indexHTML() {
  return /* html */ `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + Nitro + Qwik</title>

    <script async type="module" src="@qwik.dev/core/qwikloader.js">
      // ^ This is the QwikLoader, it's required for Qwik to work
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module">
      import { render, jsx } from "./src/client";
      import Root from "./src/root";

      /** This renders your application */
      render(document.querySelector("#root"), jsx(Root));
    </script>
  </body>
</html>
`;
}

// examples/react-ssr/src/server.tsx
/// <reference types="vite/client" />
import { renderToString } from "react-dom/server";
import App from "./App.jsx";

export default {
  async fetch(req: Request): Promise<Response> {
    const appHTML = await renderToString(<App />);
    return new Response(indexHTML(appHTML), {
      headers: {
        "Content-Type": "text/html",
      },
    });
  },
};

function indexHTML(appHTML: string) {
  return /* html */ `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + Nitro + React</title>
    ${
      import.meta.env?.DEV
        ? '<script type="module" src="/@vite/client"></script>'
        : ""
    }
  </head>
  <body>
    <div id="app">${appHTML}</div>
    <script type="module" src="${resolveEntry("src/client.tsx")}"></script>
  </body>
</html>`;
}

function resolveEntry(entry: string): string {
  if (import.meta.env?.PROD) {
    const manifest = globalThis.__VITE_MANIFEST__;
    const file = manifest?.[entry]?.file;
    if (!file) {
      throw new Error(
        manifest
          ? `Entry "${entry}" not found in Vite manifest.`
          : "Vite manifest is not available."
      );
    }
    return `/${file}`;
  }
  return `/${entry}`;
}
